# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://github.com/pre-commit/pre-commit/blob/main/.pre-commit-config.yaml

repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets